name: Seeklit

services:
  seeklit:
    image: ghcr.io/laustindasauce/seeklit:latest
    container_name: seeklit
    ports:
      - "3014:80"
    restart: always
    environment:
      SEEKLIT_CONF_FILE: /config/seeklit.conf
      SEEKLIT_ABS_URL: http://audiobookshelf:80
    volumes:
      - /mnt/volume/config/seeklit:/config
      - /mnt/volume/data/seeklit:/data # SQLite DB location
