name: Seeklit

networks:
  proxynet:
    name: audiobookshelf_default
    external: true

services:
  seeklit-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: seeklit-server:latest
    container_name: seeklit-server
    restart: always
    networks:
      - proxynet
    environment:
      SEEKLIT_CONF_FILE: /config/seeklit.conf
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./data:/config
      - ./data:/data # SQLite DB location

  seeklit-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: seeklit-client:latest
    container_name: seeklit-client
    restart: always
    networks:
      - proxynet
    environment:
      SEEKLIT_ABS_URL: http://audiobookshelf:80
      SEEKLIT_ABS_EXTERNAL_URL: http://localhost:13378
      SEEKLIT_SERVER_URL: http://seeklit-server:8416
      SEEKLIT_ADMIN_EMAIL: admin@example.com
      SEEKLIT_DISABLE_ISSUES: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    depends_on:
      - seeklit-server

  nginx:
    image: seeklit-client:latest
    container_name: seeklit-nginx
    command: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - proxynet
    depends_on:
      - seeklit-server
      - seeklit-client
